### ISSUE TITLE
gif 파일 경로 생성

### ISSUE THREAD

**Issue by swjeon-dev** [software92/todo-app#3]
add to do:
![addtodogif](https://user-images.githubusercontent.com/95457388/209030271-8a8b1193-efde-4db8-b380-23cdd9e1b734.gif)
switch to do:
![convertodogif](https://user-images.githubusercontent.com/95457388/209030277-1311302e-ba69-4ec2-9b7b-a7f3b14ed85f.gif)
drag and drop:
![dndgif](https://user-images.githubusercontent.com/95457388/209030279-79d7682f-a405-4603-9b04-36522b183536.gif)

**Comment by software92** [comment]
screen update
